### ISSUE TITLE
R&D and VAB UI

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/TestFlight#134]
Engine context menu shows one R&D button for every available config (possibly doubling the menu size); on top of that, these don't seem to work. The TF window always shows research for the active config no matter which R&D button I push.

That had the benefit of making me aware that the 1kN has three sets of reliability data, which was good. But overall, I don't think it needs many buttons and possibly even none at all:
The worst downside of the current solution is that one has to enter the VAB in order to interact with TF. I get why this is so; but I don't see myself trying to pick an engine from an existing craft. When I'm in the "interact with TF research" mindset, I will use the VAB differently than when building a vessel. I'll probably start with a clean slate and just select the engine I'm interested in. So in my opinion, it's not a question of integrating TF research and shipbuilding, but to make these tasks not tread on each other's toes.

--

If an engine has more than the max. researchable data, the text telling me so is wider than the window and needs a line break.

--

For engines having zero data, I get weird MTBF readouts. These look positively scary.

--

Advanded-Skilled-Expert buttons are a bit bland. I want to know how much I need to put on the table and what it buys me. The buttons could be made taller to accomodate the info, or, as no funds are deducted while sitting in VAB, you could display the info after the user has made a selection. Doubling back and making another selection isn't much of an UI hassle: and if the algorithm isn't too fancy, the user will quickly learn what kind of outcome to expect, so the need to double back will decrease.

--

The main menu R&D list should give an indication of progress (du / MTBF). That window is by all means wide enough to display this data.

**Comment by jwvanderbeck** [comment]
The Editor UI has massively improved over the last few days and most of the bugs in it have been fixed.

There is now an info window that is accessible from middle clicking a placed part, just like in KER.

The bug with multiple buttons has also been fixed.  As has the invalid MTBF bug.

**Comment by jwvanderbeck** [comment]
> The main menu R&D list should give an indication of progress (du / MTBF). That window is by all means wide enough to display this data.

Unfortunately this is non-trivial because the parts don't have a correct active configuration in the KSC scene, thus this information isn't available.  About the best I could do would be to display the current amount of data the part has, as that is stored in the scenario.  Not sure that one number in isolation is of much use though.

**Comment by Schnobs** [comment]
At least half of it's meaning is to be a kind of heartbeat: show the user that yes indeed, something is happening. A percentage would do for that purpose, though I'd prefer du -- as long as all engines scale from zero to 10k, that figure isn't wholly meaningless.

**Comment by jwvanderbeck** [comment]
Right but knowing you are at 5k du only means something if you know the max is 10k.  Plus bear in mind this 10k on everything is something RO is doing, it isn't a TF thing. Parts can in theory have any max data value.

I'm just concerned in this case giving that teeny amount of info might be worse than not giving it at all.  The fact that the parts are listed along with the ability to change their research lets you know they are working.

Alternatively I need to modify things so that more information is stored in the scenario rather than on the part module. Which is doable but a bit dirty especially since things like maxData are static values.

**Comment by Schnobs** [comment]
Well in that case, it's maybe better to leave it out. 
I briefly considered some kind of general progress meter (du researched / max research) but that would probably give the impression that one has to wait until it's "done". Not good, IMO.

The menus look good now, the only thing that bothers me is that the R&D window still pops up in the upper left, blocking the part list. Lower right was fine, IMO, but given that everyone has their own preferences... Could it maybe remember it's last position?

**Comment by jwvanderbeck** [comment]
It a actually **is** saved.  If you look in the settings file you can see it.  For some reason it isn't being **used** the first time it opens up and I don't know why yet.

Can you open a separate issue for this specifically please?
