### ISSUE TITLE
Tech transfer is broken

### ISSUE THREAD

**Issue by ts826848** [KSP-RO/TestFlight#177]
Reminder so I maybe can take a look later

From #RO:
```
16:15 < awang> Tech transfer?
16:16 < soundnfury> yeah, when you upgrade a part you're supposed to get a percentage
                    of the data from the old part on the new one
16:16 < soundnfury> but it only lasts for the first flight, then subtracts itself back
                    off for some reason
16:16 < soundnfury> _but_ if beforehand you hire an R&D team, you get and keep the tech
                    transfer
16:17 < soundnfury> but beware, if that takes you over the part's R&D limit, it'll just
                    keep on R&D-ing until it gets to 100%
16:17 < awang> wut
16:17 < soundnfury> (and you can't stop the R&D in the editor, you have to use the
                    spacecentre TF menu)
```

**Comment by ec429** [comment]
Proposed new design to fix all the weird and broken behaviours of Tech Transfer:

For each partname (i.e. data-having thing), store two numbers, its own local du and transferred du, separately.  The latter is recalculated when launching a new rocket, because that's the point at which the failure curves for that rockets parts are (or at least should be) set.
The transferred du is simply the weighted sum of the _local_ du of the parts listed in `techTransfer`.  Thus, TF only does _direct_ transfers, not indirect (transferred data from A to B and then from B to C); if you want indirect transfers, put multi-generation lists into your configs.  (Basically everyone does this already, meaning that this combines with the indirect transfers to go quadratic, so most parts start with full data by the mid-game.  Especially as the `techTransferMax` that RealismOverhaul tries to use doesn't appear to actually exist in TF.)

Advantages of this system:
1. There's no special "transfer" event that has to happen precisely once, and after which no further data collected on the old engine can be transferred to the new one.  This also avoids the current situation with single-generation techTransfers like the RD-100 series, where you have to buy the RD-102 and poke its RnD in order to propagate your RD-101 data into the RD-103 (but don't have to actually _fly_ the RD-102).
2. Cycles in the `techTransfer` graph can be allowed, without resulting in infinite replication of du.  This means we can:
  (a) link together different parts at the same tech level, like the three CECE variants (actually we already do that, but it's currently broken owing to aforementioned possibility of infinite du replication).
  (b) have `techTransfer` from newer to older engines, as well: experience with the _next_ generation is just as relevant to an engine as is the _previous_ generation, and older engines often keep flying for at least a short while after the newer ones are unlocked.

If I get a round tuit, I might whip up a PR to implement this (and add `techTransferMax`, too).

**Comment by pap1723** [comment]
That is a great idea!

**Comment by jwvanderbeck** [comment]
This system was rewritten in 2.0 and this issue should not longer be present.  Please open a new issue if it is observed.  Thank you.
