### ISSUE TITLE
display likelyhood of ignition failure?

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/TestFlight#183]
I am playing RP-1 on KSP 131. I find playing with the frequent ignition failures quite challenging. Looks like otherwise similar engines can be vastly different here.

It'd be great if the information about ignition failure rates could be displayed in the VAB and in the testflight interface during flight mode. It'd be great if in the flight mode window this could also include the effect of dynamic pressure as I understand this has an effect, too. (It does, doesn'T it? )

**Comment by jwvanderbeck** [comment]
Dynamic pressure will generally only have an effect if the engine is traditionally a ground lit engine, not designed to be air lit.

**Comment by glilienthal** [comment]
I'd love to bump this up. could the chance of successful ignition (maybe ignoring dynamic pressure if this simplifies things) be displayed?

**Comment by siimav** [comment]
Implemented in 411011578768a266592581516e50ba5afe7e4a55

**Comment by glilienthal** [comment]
This is very cool. No more digging through config files. - I'll give it a thorough testing, once RL stops annoyingly intervening with KSP. 

Thank you, @siimav

**Comment by siimav** [comment]
Latest release has ignition reliability rates shown in the VAB and also in the part info panel. There's also a difficulty setting that allows disabling dynamic pressure penalties. My own experience with that feature is that sometimes the Q values are way off and thus cause the ignition chance to be unfairly low.

**Comment by jwvanderbeck** [comment]
> sometimes the Q values are way off 

What do you mean here? That TF is using incorrect pressure values? This shouldn't be the case.

I'm not sure I like the idea of ignition failures being disabled on anything lower than hard difficulty.  Ignition failures are a large part of the game play of TF.

**Comment by siimav** [comment]
I didn't actually disable the ignition failures entirely on difficulties less than hard. I just did it for the dynamic-pressure-based penalties that TF used to apply by-default. [See Here.](https://github.com/KSP-RO/TestFlight/commit/01a9552e3a5a81e9469568d9eeb3f13657a81abc)

The reasoning behind the decision is that this feature just doesn't work consistently enough to be enabled by-default for everyone. Based on my tests, most of the time, the interstage fairing was correctly shielding my engine from external dynamic pressure. Sometimes for no apparent reason, it just wasn't doing it at all. On one case I was consistently getting 40kPa of dynamic pressure at an altitude of 100km+. I'm sure that TF is doing everything correctly here but the issue is on the side of stock KSP or ModularFlightIntegrator. Another side of this dyn-pressure based penalty is that this information is not 
surfaced to the user in any way and usually just leaves him frustrated when his engines almost never ignite at high Q.

**Comment by Starstrider42** [comment]
> On one case I was consistently getting 40kPa of dynamic pressure at an altitude of 100km+. I'm sure that TF is doing everything correctly here but the issue is on the side of stock KSP or ModularFlightIntegrator.

If you have dynamic pressure at >100 km then I assume you're playing with RSS/RO? Could it be an issue with one of those mods or TF's interaction with them? I play TF on stock, and I frequently get ignition failures at 10 km (which is around max Q for my designs) but never at 40 km.

**Comment by jwvanderbeck** [comment]
TF was made specifically for RSS/RO so I doubt it.
