### ISSUE TITLE
Being able to generate DU's through static fires

### ISSUE THREAD

**Issue by Tonas1997** [KSP-RO/TestFlight#194]
I've read #61 and, while I get the logic behind R&D teams and only getting data units by flying the engines, TestFlight could have the option to generate data through "clamped", static-fire setups. This aims to simulate integrated stage testing - as it happens in real-life - with assembled rocket stages in a more fun way than just throwing money at research teams or risk losing missions to faulty engines.

Also, it would allow players to exploit and design static fire setups that, in the presence of TestFlight, could have an actual usefulness (not to mention giving a job to the dedicated static fire scaffolds that come with some KerbalKonstructs packs).

As this will certainly be controversial, the possibility of generating data units with clamped vessels should be optional. Further development could introduce some interesting balance between getting DU's from R&D or static-firing.

**Comment by jwvanderbeck** [comment]
Static firing was intentionally removed in favor of the R&D system.  From a gameplay perspective static firing may be real but isn't a good or fun mechanic.  When it existed everyone felt obligated to put every engine on a stand, fire it up and go watch TV/YouTube until it was good.  Game design is all about risk vs reward and static fire is 0 risk for lots of reward.  The R&D system forces you to trade funds, for the data.

**Comment by Tonas1997** [comment]
Yes, that makes sense. The suggestion was posted as an optional mechanic, as most people seem to enjoy the current R&D system. I reckon RP-0 would never use it, but others could.

**Comment by KerballOne** [comment]
> intentionally removed in favor of the R&D system

This should be reconsidered now that R&D is gone.  
There does not appear to be a way to get DUs at all, other than testing in production ( a real rocket leaving the launch pad ).  That's not realistic, and not even fun.  

> When it existed everyone felt obligated to put every engine on a stand, fire it up and go watch TV/YouTube until it was good. 

No more so than with any flight managed by KOS or MechJeb ;)

>  Game design is all about risk vs reward and static fire is 0 risk for lots of reward. The R&D system forces you to trade funds for the data.

I get that.  Real rocket design is also about mitigating unnecessary risk too.  There is no way a space program will not test engines prior to mission with static fires.  But you're right, there is always a cost to it.
Simulation doesn't cost any funds when reverted back, but also DUs don't save either.  When you actually build a test stand, fire with launch clamps providing resources,... there is still no costs?  I guess recovery returns all funds.  But RP-1/KCT does charge time and funds for rollout and LC refurb.  Maybe they should also track resources consumed by LC clamps.

I haven't played with earlier versions with R&D.  So I don't know, but it seems like it was a simple way to get DUs prior to an expensive mission.  There is still reference to it in the SpaceCenter TestFlight app menu.  But since it looks like nothing will replace/fix R&D, then please reconsider allowing static fire data collection.
Thank you.



+1 @siimav

**Comment by siimav** [comment]
The reliability numbers of all engines already assume that static fires have been conducted. So no, generating DU through static fires will never become a thing.

**Comment by KerballOne** [comment]
Okay, and R&D isn't going to be replaced or fixed?  Any other options for getting DU prior to mission?

**Comment by jwvanderbeck** [comment]
Hi.  The point siimav was trying to make is that the numbers are all set so that the very first time you fly an engine, it's reliability is the same as the very first time it was flown in real life.  Therefore no static testing, no R&D is necessary to mimic history.

**Comment by KerballOne** [comment]
Alright, that's fair.
