### ISSUE TITLE
Alt-cloning an engine confuses PAW testflight stats

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/TestFlight#265]
- create a .craft with an engine as non-root part (or use attached; needs RO+ROEngines)
- load the .craft (via Craft Manager - don't know if relevant, but wouldn't be surprised)
- alt-click the engine to clone it, place the clone on the vessel
- open PAW of original and cloned engines, compare testflight blocks

Original is fine; cloned is... confused. In this example: shows rated continuous time on an engine that has no such value; shows the wrong earned DU; doesn't update values when switching configs.

Loading a .craft is a necessary step; doesn't occur when alt-clicking a part newly-placed from parts catalog. Haven't tried loading without Craft Manager.

[wat.craft.zip](https://github.com/KSP-RO/TestFlight/files/10949898/wat.craft.zip)

![screenshot98](https://user-images.githubusercontent.com/5061230/224521999-359b0d78-58c9-4632-a560-0c5fc8d88791.png)

**Comment by Falki-git** [comment]
I tried to troubleshoot this, but have limited knowledge and couldn't reverse engineer it fully.

Yes, it only happens when cloning engines that are already attached to the loaded vessel. Testflight config nodes are taken from the saved .craft file which doesn't contain all the needed nodes to populate the PAW correctly. When cloning a newly placed part, it works ok cause the original has all the needed nodes taken from the persistent save file.

Solution that I see is detecting when passed config doesn't contain the needed nodes and load a new config from the save file, but that feels like a patch, not a real solution. Someone with more knowledge should look at this.

For now, I can only offer a workaround:

- load the craft
- clone an engine, cloned PAW gets confused
- save the craft
- load the craft again, cloned PAW is normal again

**Comment by siimav** [comment]
Same as #247
