### ISSUE TITLE
Allow "R&D" teams like BARIS

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/TestFlight#46]
So you can pay money and (in-game) time to do non-flying research. Per discussion in IRC.

**Comment by jwvanderbeck** [comment]
I think this should work as follows..

First, need to add a TF window the Space Center scene.  Really needs to be done anyway.  Probably make that window operate in the toolbar style similar to KCT.  Not positive yet.  In that window have an R&D tab.

In the R&D tab you can hire teams of scientists and engineers.  Each team can be assigned to a single part for R&D.  Any active team will continually subtract funds over time and add Data Units to their assigned part.  Larger teams cost more funds but apply data at a faster rate.  There should be a way to increase and decrease team size, change assigned part, and buttons for hiring new teams and firing existing teams.

Further more once this is in, I think I will be removing the ability to do static testing and make it so that parts need to be moving in order to accrue flight data.

**Comment by NathanKell** [comment]
That sounds good to me. I would actually suggest doing it as a third tab in the R&D screen (is that available in sandbox, though?) rather than a buildingless menu.

I would also suggest, BARIS-like, a "max R&D" per part.

**Comment by jwvanderbeck** [comment]
> That sounds good to me. I would actually suggest doing it as a third tab in the R&D screen (is that available in sandbox, though?) rather than a buildingless menu.

That building can't be accessed in Sandbox

> I would also suggest, BARIS-like, a "max R&D" per part.

Ah yes I knew I forgot something.  Yes parts should have a maximum amount of flight data that can be researched by R&D teams.  In addition, the ratio of funds & time to data should be reduced as that point is approached

**Comment by diomedea** [comment]
my 2 cents. 
Believe the additional research and effect on parts reliability improvements could also be tied to a new strategy (set in the Admin building). The amount of effort in the strategy would set the size of the R&D teams available, possibly the efficiency of the research conducted, certainly the funds expended over time.

**Comment by jwvanderbeck** [comment]
This is a good idea, though I don't know how moddable that system is, as i've never looked.  But yeah if it is doable, this is a great idea.  Never would have thought of it myself since I never bother with strategies.  Have to figure out its balance though because my understanding of the existing strategies is they give one thing and take another.  Maybe allow you to exchange some prestige for better engineers?

**Comment by jwvanderbeck** [comment]
This feature is coming in the next release!
