### ISSUE TITLE
Don't throw errors when loading TestFlightContracts if ContractConfigurator isn't present

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#79]
This is ugly and should be wrapped in a try/catch.

**Comment by jwvanderbeck** [comment]
Did I seriously not fix this yet?

**Comment by jwvanderbeck** [comment]
Actually i'm not sure if I have any control over this, as I don't think there is any point where I explicitly load  the dll and thus could wrap it.  Seems to be up to KSP entirely, but @NathanKell please correct me if I am wrong.

**Comment by NathanKell** [comment]
If you use a separate dll that references both you and CC, and if both you and CC have KSPAssembly tags, you can add KSPAssembly required tags in the separate dll and it will gracefully fail if its reqs aren't met.

**Comment by jwvanderbeck** [comment]
I do have the CC handling in a separate DLL that only deals with that.  I'll see if I can figure out the KSPAssembly bit.

Thanks.

**Comment by NathanKell** [comment]
Sure! For an example you can check SolverEngines, and then how
RealFuels.dll depends on it.

**Comment by jwvanderbeck** [comment]
Sorry can you point me to it? I can't find the file in question.

**Comment by NathanKell** [comment]
https://github.com/KSP-RO/SolverEngines/blob/master/SolverEngines/Properties/AssemblyInfo.cs#L38
https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/assembly/AssemblyInfoRF.in#L30

Note: this depends on CC (hi @nightingale !) also having a KSPAssembly tag. But it does, because that's the sort of thing @nightingale would do. :D
https://github.com/jrossignol/ContractConfigurator/blob/master/source/ContractConfigurator/Properties/AssemblyInfo.cs#L39

So in your spare dll you'd do something like
[assembly: KSPAssemblyDependency("TestFlight", x, y)]
[assembly: KSPAssemblyDependency("ContractConfigurator", z, w)]
Where x,y are the major and minor versions of TestFlight the dll requires, and z,w are the same for CC.

**Comment by jwvanderbeck** [comment]
So those lines are declaring a dependency and on the other side you are declaring what is supplies.

**Comment by NathanKell** [comment]
Yep!

**Comment by NathanKell** [comment]
With that done, KSP will manage load order for you, too :)

**Comment by jwvanderbeck** [comment]
Fixed in: https://github.com/KSP-RO/TestFlight/commit/8a6988dc8dc4d9af9872286faf44898ab443396a
