### ISSUE TITLE
TestFlightExtended

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#95]
@jwvanderbeck

have been making failures for weeks :) looky
https://github.com/anxcon/TestFlight_Extended
would love your feedback and any failure ideas :) what i have checked in is what is tested, been through several mods but untested as was waiting for 1.0.5

also with your absence of...months...i was about to make fork and start adding a few things to TF framework for 1.0.5, though you know the framework better than i, perhaps you'd like to add them :) and i'll stick to handling the failures themselves?

ever use IRC to communicate?
prolly better than rambling on :)

**Comment by jwvanderbeck** [comment]
Most excellent!

There will be a new version of TF released here soon with KSP 1.0.5 support.  **Please be aware** there are some API changes due to a conversion to using double precision internally for failure rates.  You can see the *tentative* release notes here: 

https://github.com/KSP-RO/TestFlight/issues/93

I think it is awesome that you are doing this.  I am not really back so to speak, but you are welcome to contribute to the mod, especially now that it is part of KSP-RO.  I won't be spending much time on active development but I will try to "be around" for questions, code review, PRs, etc.

**Comment by anxcon** [comment]
i think everything i used is fairly simple and non breaking from your changes
feel free to browse the failure list and let me know what you think of the code :)

**Comment by jwvanderbeck** [comment]
Yeah I think it only affects TestFlightReliability modules which you don't appear to have any of, so you should be good there :)

It was late last night when I saw your post.  Just browsed it briefly now this morning and looks good :)

**Comment by anxcon** [comment]
well if you wont be around much, feel free to give me perms to accept PRs/release etc :) reason i had made TestFlightExtended was because you were awol 5 months, and i didn't want to fork it incase a return
