### ISSUE TITLE
TestFlightFailureBase > Failed

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#96]
@jwvanderbeck
this seems to be a property, just get/set
from browsing code i see nowhere this gets saved?
does this mean failures dont save and restarting ksp fixes?:|

seems like should be a KSPField unless i am missing something?:)
but then in the core i do not see saving failed modules
so OnStart() would need to grab failures, check if failed, setup?

**Comment by jwvanderbeck** [comment]
That is entirely possible.  Making sure things persisted properly between saves was one of the biggest, if not the biggest, headache I had when working on this.  It drove me crazy.

As you say it probably isn't as simple as just persistent the value.  Will need to look into it.

**Comment by anxcon** [comment]
from browsing code

TestFlightFailureBase.Failed needs to be a persistent saved value
and core.OnStart needs to grab all failures and check failed, setting core.activefailure
or TFFB.OnStart() telling core its failed

beyond that i think extensions of TFFB would do the work of re applying failure effects with OnStart, as some of the partmodules i am breaking dont use a persistent field, and those who do, TFFB is losing failed flag for :)

**Comment by jwvanderbeck** [comment]
I took a look at this today and it seems to be more involved.  Even if the failure flag isn't retained, the state of the part is still saved in the persistence store.

So if for example and engine fails and is disabled, that disabled state is still saved in the game because it is the part's current state and KSP obviously saves that by default.  If you were to reload the game, that failure would still be there because it was part of the state that was saved.

In fact something like reduced thrust, if TF saved that and re-applied it, would end up being a **double** failure upon reload.  Once by the game saving the part state and again when it was re-applied.

I think this all works as expected with the failures I had made.  If there are failures you have made where it isn't working as expected, can you please show me an example so I can think of the best way to handle it?

**Comment by anxcon** [comment]
that only works if the part/module that is failing has the effected field ispersistent=true, which many are not - so thinking that giving failure a persistent kspfield failed, then letting failure modules check and reapply during onstart, would solve it......or...failureFieldPersistent long name, but have base check that onstart and if false call dofailure, leaving derived modules from having to do anything aside from set flag once during start or such

unless i miss something, maxthrust failure changes minFuelFlow and maxFuelFlow which are not saved, only loaded from the original config curves, as well when i launched a ship, saved, returned, the shutdown failures i had were gone, or rather not in failed state

if you want specific cases for my failures, GimbalSpeed changes ModuleGimbal.gimbalResponseSpeed which ispersistent=false, and while i can override it, i cant tell during load if the the failure is in failed state, only add my own failed flag on per module bases, so trying to think up a global solution to not need special code on per module basis

**Comment by jwvanderbeck** [comment]
My point is that some failures make changes to stock KSP attributes which KSP itself would be persisting.  Not all of them, but some of them.  I'm afraid of messing up what is there and causing double failures without a much better look at the system which will probably come as part of the config rewrites.
