### ISSUE TITLE
TestFlight data at SpaceCenter

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#98]
@jwvanderbeck
wanted to take current data of parts and show them at main KSC view / do stuff
i checked through the prefabs, fetch core module, check currentFlightData, which i guess would be wrong as that shows 0 heh, so where to grab the data at?

**Comment by jwvanderbeck** [comment]
Hmm bear in mind that I haven't looked at this code in a long time :)

Couple things come to mind.  First, you should use TestFlightCore.GetFlightData() rather than accessing the variable directly.

Secondly, if you aren't actually in flight then that means there isn't an actual part instance loaded which might be the problem.  I can't recall the details but I do recall having a lot of issues on that front.

Try this instead.  The Scenario stores the flight data, well obviously.  So while it won't have up to date data **during** a flight, if you are just sitting at KSC then it should be up to date.  So with that said try getting it from there instead:

            if (TestFlightManagerScenario.Instance != null)
            {
                TestFlightPartData partData = TestFlightManagerScenario.Instance.GetPartDataForPart(TestFlightUtil.GetFullPartName(part));
                return partData.GetFloat("flightData");
            }

**Comment by anxcon** [comment]
worked
